#!/bin/bash
set -e

# Interactive or manual secret configuration.
# Writes to docker/.env or k8s/secrets.yml depending on deployment type.
# Usage: ./scripts/configure-secrets.sh <docker|k8s> <dns_provider>

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
DEPLOYMENT="${1}"
DNS_PROVIDER="${2}"

if [ -z "${DEPLOYMENT}" ] || [ -z "${DNS_PROVIDER}" ]; then
  echo "Usage: $0 <docker|k8s> <dns_provider>"
  exit 1
fi

# --- Load DNS provider ---

DNS_SCRIPT="${SCRIPT_DIR}/dns/${DNS_PROVIDER}.sh"
if [ ! -f "${DNS_SCRIPT}" ]; then
  echo "ERROR: DNS provider '${DNS_PROVIDER}' not found."
  echo "Available providers:"
  ls "${SCRIPT_DIR}/dns/"*.sh 2>/dev/null | xargs -I{} basename {} .sh
  exit 1
fi
. "${DNS_SCRIPT}"

# --- Ask input mode ---

echo ""
echo "=== Secret Configuration ==="
echo ""
echo "1) Enter values interactively"
echo "2) Edit the config file manually"
printf "Choice [1/2]: " && read -er INPUT_MODE

case "${INPUT_MODE}" in
  2) manual_mode=true ;;
  *) manual_mode=false ;;
esac

# --- Manual mode ---

if [ "${manual_mode}" = true ]; then
  if [ "${DEPLOYMENT}" = "docker" ]; then
    TARGET="${ROOT_DIR}/docker/.env"
    EXAMPLE="${ROOT_DIR}/docker/.env.example"
    if [ ! -f "${TARGET}" ]; then
      cp "${EXAMPLE}" "${TARGET}"
    fi
    chmod 600 "${TARGET}"
    echo ""
    echo "Edit your config file:"
    echo "  ${TARGET}"
    echo ""
    if [ -n "${EDITOR}" ]; then
      printf "Open in editor now? [Y/n]: " && read -er OPEN_EDITOR
      case "${OPEN_EDITOR}" in
        n|N) ;;
        *) ${EDITOR} "${TARGET}" ;;
      esac
    fi
  else
    TARGET="${ROOT_DIR}/k8s/secrets.yml"
    EXAMPLE="${ROOT_DIR}/k8s/secrets.yml.example"
    if [ ! -f "${TARGET}" ]; then
      cp "${EXAMPLE}" "${TARGET}"
    fi
    chmod 600 "${TARGET}"
    echo ""
    echo "Edit your config file:"
    echo "  ${TARGET}"
    echo ""
    if [ -n "${EDITOR}" ]; then
      printf "Open in editor now? [Y/n]: " && read -er OPEN_EDITOR
      case "${OPEN_EDITOR}" in
        n|N) ;;
        *) ${EDITOR} "${TARGET}" ;;
      esac
    fi
  fi
  echo ""
  printf "Press Enter when done editing..." && read -er _
  return 0 2>/dev/null || exit 0
fi

# --- Interactive mode ---

echo ""
echo "=== Server Settings ==="
printf "Domain (e.g. git.yourdomain.com): " && read -er HOSTNAME
printf "SSH port [2222]: " && read -er SSH_PORT
SSH_PORT="${SSH_PORT:-2222}"

echo ""
echo "=== Database ==="
printf "Postgres database name [forgejo]: " && read -er POSTGRES_DB
POSTGRES_DB="${POSTGRES_DB:-forgejo}"
printf "Postgres user [forgejo]: " && read -er POSTGRES_USER
POSTGRES_USER="${POSTGRES_USER:-forgejo}"

echo ""
echo "Generating a strong database password..."
POSTGRES_PASSWORD=$(openssl rand -hex 24)
echo "Password: ${POSTGRES_PASSWORD}"

echo ""
echo "=== ACME / Let's Encrypt ==="
printf "Email for Let's Encrypt: " && read -er ACME_EMAIL

# DNS provider credentials
dns_prompt_credentials

# --- Write config ---

if [ "${DEPLOYMENT}" = "docker" ]; then
  TARGET="${ROOT_DIR}/docker/.env"
  cat > "${TARGET}" <<EOF
# Generated by run.sh — $(date -Iseconds)

# General
TZ=Europe/Stockholm
HOSTNAME=${HOSTNAME}

# User / Permissions
UID=1000
GID=1000
SSH_PORT=${SSH_PORT}

# PostgreSQL
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Forgejo Server
ROOT_URL=http://localhost:3000/

# Forgejo Visibility
FORGEJO_DISABLE_REGISTRATION=true
FORGEJO_REQUIRE_SIGNIN=true
FORGEJO_DEFAULT_REPO_PRIVATE=true
FORGEJO_DEFAULT_USER_VISIBILITY=private
FORGEJO_DEFAULT_ORG_VISIBILITY=private

# Backups
BACKUP_CRON=0 3 * * *
BACKUP_KEEP_DAYS=30

# ACME
ACME_EMAIL=${ACME_EMAIL}

# DNS Provider (${DNS_PROVIDER})
$(dns_docker_env)
EOF

else
  TARGET="${ROOT_DIR}/k8s/secrets.yml"
  cat > "${TARGET}" <<EOF
# Generated by run.sh — $(date -Iseconds)
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-secrets
  namespace: forgejo
type: Opaque
stringData:
  HOSTNAME: ${HOSTNAME}
  SSH_PORT: "${SSH_PORT}"
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  ACME_EMAIL: ${ACME_EMAIL}
$(dns_k8s_secret)
EOF
fi

chmod 600 "${TARGET}"
echo ""
echo "Config written to: ${TARGET}"
